name: base
channels:
  - conda-forge
dependencies:
  - python=3.9
  - geopandas==0.14.3
  - seaborn==0.13.2
  - jupyterlab==4.1.2
  - plotly==5.19.0
  - gdal==3.8.4
  - ipywidgets==8.1.2
  - folium==0.15.1
  - rasterio==1.3.9
  - leafmap==0.31.1
  - keplergl==0.3.2
  - pydeck==0.8.0
  - jupyter_contrib_nbextensions==0.7.0
  - nodejs==20.9.0
  - xarray_leaflet==0.2.3
  - jupyter-server-proxy==4.1.0
  - gcc
  - pip:
    - localtileserver==0.10.1
